server:
  port: 8084
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - DELETE
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: GATEWAY-SERVICE
timeout:
  value: 604800000
secret:
  value: 1234567